FROM mcr.microsoft.com/dotnet/sdk:10.0  AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p fd092b11-86a2-4a31-9949-875ac31369ce
RUN chmod 644 openiddict.pfx

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "ReportBuilder.HttpApi.Host.dll"]